/**
 * ═══════════════════════════════════════════════════════════════════
 *  VirtualVigyan — Universal Chemical Species Database
 * ═══════════════════════════════════════════════════════════════════
 *
 *  Comprehensive physical, thermodynamic, and optical constants for
 *  all common reagents, salts, acids, bases, metals, indicators, and gases.
 *  100% deterministic — zero server/AI dependency.
 * ═══════════════════════════════════════════════════════════════════
 */

export type ChemicalType =
  | 'acid'
  | 'base'
  | 'salt'
  | 'metal'
  | 'gas'
  | 'water'
  | 'indicator'
  | 'organic'
  | 'oxide';

export type PhysicalState = 'liquid' | 'solid' | 'gas' | 'aqueous';

export interface ChemicalSpecies {
  id: string;
  name: string;
  formula: string;
  molarMass: number; // g/mol
  density: number; // g/mL or g/cm³
  type: ChemicalType;
  baseColor: string; // Default visual appearance (aqueous/pure)
  stateAtRoomTemp: PhysicalState;
  pKa?: number;
  solubilityLimit?: number; // g / 100 mL H2O at 25°C (Infinity = fully miscible, < 0.1 = insoluble precipitate)
  hazards: string[];
  commonConcentrationM?: number; // Standard bench reagent molarity
  description: string;
}

export const CHEMICAL_DATABASE: Record<string, ChemicalSpecies> = {
  // ── Solvents ──
  h2o: {
    id: 'h2o',
    name: 'Distilled Water',
    formula: 'H₂O',
    molarMass: 18.015,
    density: 1.0,
    type: 'water',
    baseColor: 'rgba(230, 244, 255, 0.45)',
    stateAtRoomTemp: 'liquid',
    solubilityLimit: Infinity,
    hazards: [],
    description: 'Deionized neutral solvent (pH ~ 7.00).',
  },

  // ── Mineral & Organic Acids ──
  hcl: {
    id: 'hcl',
    name: 'Hydrochloric Acid',
    formula: 'HCl',
    molarMass: 36.46,
    density: 1.05,
    type: 'acid',
    baseColor: 'rgba(240, 249, 255, 0.50)',
    stateAtRoomTemp: 'aqueous',
    pKa: -6.3,
    solubilityLimit: Infinity,
    hazards: ['Corrosive', 'Causes severe skin burns', 'Acid vapor irritant'],
    commonConcentrationM: 0.1,
    description: 'Strong monoprotic mineral acid, fully dissociated in water.',
  },
  h2so4: {
    id: 'h2so4',
    name: 'Sulfuric Acid',
    formula: 'H₂SO₄',
    molarMass: 98.08,
    density: 1.15,
    type: 'acid',
    baseColor: 'rgba(238, 242, 255, 0.55)',
    stateAtRoomTemp: 'aqueous',
    pKa: -3.0,
    solubilityLimit: Infinity,
    hazards: ['Extremely Corrosive', 'Highly Exothermic Dilution', 'Severe Burns'],
    commonConcentrationM: 0.1,
    description: 'Strong diprotic acid; violent heat released upon rapid water addition.',
  },
  hno3: {
    id: 'hno3',
    name: 'Nitric Acid',
    formula: 'HNO₃',
    molarMass: 63.01,
    density: 1.10,
    type: 'acid',
    baseColor: 'rgba(254, 249, 195, 0.45)',
    stateAtRoomTemp: 'aqueous',
    pKa: -1.4,
    solubilityLimit: Infinity,
    hazards: ['Strong Oxidizer', 'Corrosive', 'Toxic NO₂ Fumes'],
    commonConcentrationM: 0.1,
    description: 'Strong oxidizing acid capable of reacting with copper and organic matter.',
  },
  ch3cooh: {
    id: 'ch3cooh',
    name: 'Acetic Acid',
    formula: 'CH₃COOH',
    molarMass: 60.05,
    density: 1.02,
    type: 'acid',
    baseColor: 'rgba(248, 250, 252, 0.50)',
    stateAtRoomTemp: 'aqueous',
    pKa: 4.76,
    solubilityLimit: Infinity,
    hazards: ['Irritant', 'Pungent Vinegar Odor'],
    commonConcentrationM: 0.1,
    description: 'Weak organic carboxylic acid with partial dissociation.',
  },
  oxalic_acid: {
    id: 'oxalic_acid',
    name: 'Oxalic Acid',
    formula: 'H₂C₂O₄',
    molarMass: 90.03,
    density: 1.05,
    type: 'acid',
    baseColor: 'rgba(241, 245, 249, 0.40)',
    stateAtRoomTemp: 'aqueous',
    pKa: 1.25,
    solubilityLimit: 14.3,
    hazards: ['Harmful if swallowed', 'Skin and eye irritant'],
    commonConcentrationM: 0.05,
    description: 'Primary standard dicarboxylic acid, used in redox and acid-base standardization.',
  },

  // ── Bases & Alkalis ──
  naoh: {
    id: 'naoh',
    name: 'Sodium Hydroxide',
    formula: 'NaOH',
    molarMass: 40.00,
    density: 1.04,
    type: 'base',
    baseColor: 'rgba(240, 253, 250, 0.50)',
    stateAtRoomTemp: 'aqueous',
    pKa: 13.8,
    solubilityLimit: 109,
    hazards: ['Caustic / Corrosive', 'Slippery touch', 'Causes severe eye damage'],
    commonConcentrationM: 0.1,
    description: 'Strong caustic alkali, dissociates completely into Na⁺ and OH⁻.',
  },
  koh: {
    id: 'koh',
    name: 'Potassium Hydroxide',
    formula: 'KOH',
    molarMass: 56.11,
    density: 1.05,
    type: 'base',
    baseColor: 'rgba(240, 253, 250, 0.50)',
    stateAtRoomTemp: 'aqueous',
    pKa: 13.5,
    solubilityLimit: 121,
    hazards: ['Caustic / Corrosive', 'Eye Damage'],
    commonConcentrationM: 0.1,
    description: 'Strong alkali with high saponification and neutralization power.',
  },
  nh4oh: {
    id: 'nh4oh',
    name: 'Ammonium Hydroxide',
    formula: 'NH₄OH',
    molarMass: 35.05,
    density: 0.95,
    type: 'base',
    baseColor: 'rgba(241, 245, 249, 0.45)',
    stateAtRoomTemp: 'aqueous',
    pKa: 9.25,
    solubilityLimit: Infinity,
    hazards: ['Pungent suffocating odor', 'Respiratory irritant'],
    commonConcentrationM: 0.1,
    description: 'Weak volatile nitrogenous base (aqueous ammonia).',
  },
  ca_oh2: {
    id: 'ca_oh2',
    name: 'Calcium Hydroxide (Limewater)',
    formula: 'Ca(OH)₂',
    molarMass: 74.09,
    density: 1.02,
    type: 'base',
    baseColor: 'rgba(248, 250, 252, 0.65)',
    stateAtRoomTemp: 'aqueous',
    pKa: 12.4,
    solubilityLimit: 0.17, // Sparingly soluble
    hazards: ['Skin & eye irritant'],
    commonConcentrationM: 0.02,
    description: 'Sparingly soluble limewater, turns milky white when bubbling CO₂ gas.',
  },

  // ── Carbonates & Common Inorganic Salts ──
  na2co3: {
    id: 'na2co3',
    name: 'Sodium Carbonate',
    formula: 'Na₂CO₃',
    molarMass: 105.99,
    density: 1.05,
    type: 'salt',
    baseColor: 'rgba(241, 245, 249, 0.40)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 21.5,
    hazards: ['Mild irritant'],
    commonConcentrationM: 0.05,
    description: 'Basic salt that vigorously effervesces CO₂ gas when mixed with acid.',
  },
  nahco3: {
    id: 'nahco3',
    name: 'Sodium Bicarbonate',
    formula: 'NaHCO₃',
    molarMass: 84.01,
    density: 1.03,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.40)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 9.6,
    hazards: [],
    commonConcentrationM: 0.1,
    description: 'Bicarbonate salt, rapidly reacts with acids producing carbon dioxide foam.',
  },
  nacl: {
    id: 'nacl',
    name: 'Sodium Chloride',
    formula: 'NaCl',
    molarMass: 58.44,
    density: 1.02,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.35)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 36.0,
    hazards: [],
    commonConcentrationM: 0.1,
    description: 'Neutral table salt solution (pH ~ 7.00).',
  },
  bacl2: {
    id: 'bacl2',
    name: 'Barium Chloride',
    formula: 'BaCl₂',
    molarMass: 208.23,
    density: 1.05,
    type: 'salt',
    baseColor: 'rgba(241, 245, 249, 0.40)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 35.8,
    hazards: ['Toxic if swallowed'],
    commonConcentrationM: 0.1,
    description: 'Soluble barium salt, precipitates dense white BaSO₄ with sulfate ions.',
  },
  na2so4: {
    id: 'na2so4',
    name: 'Sodium Sulfate',
    formula: 'Na₂SO₄',
    molarMass: 142.04,
    density: 1.04,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.35)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 28.1,
    hazards: [],
    commonConcentrationM: 0.1,
    description: 'Neutral sulfate salt used for gravimetric and precipitation practicals.',
  },
  agno3: {
    id: 'agno3',
    name: 'Silver Nitrate',
    formula: 'AgNO₃',
    molarMass: 169.87,
    density: 1.06,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.40)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 216,
    hazards: ['Corrosive', 'Stains skin dark', 'Harmful to aquatic life'],
    commonConcentrationM: 0.1,
    description: 'Soluble silver salt, forms insoluble curdy white AgCl precipitate with chlorides.',
  },
  ki: {
    id: 'ki',
    name: 'Potassium Iodide',
    formula: 'KI',
    molarMass: 166.00,
    density: 1.05,
    type: 'salt',
    baseColor: 'rgba(254, 252, 232, 0.45)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 144,
    hazards: [],
    commonConcentrationM: 0.1,
    description: 'Iodide salt that yields dazzling golden-yellow PbI₂ crystals with lead salts.',
  },
  pb_no3_2: {
    id: 'pb_no3_2',
    name: 'Lead(II) Nitrate',
    formula: 'Pb(NO₃)₂',
    molarMass: 331.20,
    density: 1.08,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.40)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 52.2,
    hazards: ['Toxic Heavy Metal', 'Reproductive hazard'],
    commonConcentrationM: 0.1,
    description: 'Soluble lead salt used in double displacement golden-spangle reactions.',
  },

  // ── Transition Metal Salts ──
  cuso4: {
    id: 'cuso4',
    name: 'Copper(II) Sulfate',
    formula: 'CuSO₄',
    molarMass: 159.61,
    density: 1.06,
    type: 'salt',
    baseColor: 'rgba(14, 165, 233, 0.75)', // Vivid Cyan-Blue
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 20.7,
    hazards: ['Harmful if swallowed', 'Aquatic toxin'],
    commonConcentrationM: 0.1,
    description: 'Brilliant deep blue copper salt; undergoes single displacement with zinc or iron.',
  },
  feso4: {
    id: 'feso4',
    name: 'Iron(II) Sulfate',
    formula: 'FeSO₄',
    molarMass: 151.91,
    density: 1.04,
    type: 'salt',
    baseColor: 'rgba(134, 239, 172, 0.55)', // Pale green
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 25.6,
    hazards: ['Harmful if swallowed'],
    commonConcentrationM: 0.1,
    description: 'Green vitriol; reducing agent titrated against KMnO₄.',
  },
  fecl3: {
    id: 'fecl3',
    name: 'Iron(III) Chloride',
    formula: 'FeCl₃',
    molarMass: 162.20,
    density: 1.08,
    type: 'salt',
    baseColor: 'rgba(180, 83, 9, 0.75)', // Amber brownish-yellow
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 91.8,
    hazards: ['Corrosive', 'Stains skin and clothing'],
    commonConcentrationM: 0.1,
    description: 'Amber ferric salt; hydrolyzes to form acidic brownish solutions.',
  },
  kmno4: {
    id: 'kmno4',
    name: 'Potassium Permanganate',
    formula: 'KMnO₄',
    molarMass: 158.03,
    density: 1.06,
    type: 'salt',
    baseColor: 'rgba(126, 34, 206, 0.88)', // Deep royal purple
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 6.4,
    hazards: ['Strong Oxidizer', 'Stains skin dark brown', 'Harmful if swallowed'],
    commonConcentrationM: 0.02,
    description: 'Self-indicating intense purple oxidizing reagent, decolorizes in acidic redox reactions.',
  },
  k2cr2o7: {
    id: 'k2cr2o7',
    name: 'Potassium Dichromate',
    formula: 'K₂Cr₂O₇',
    molarMass: 294.18,
    density: 1.08,
    type: 'salt',
    baseColor: 'rgba(234, 88, 12, 0.88)', // Vivid Orange
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 12.3,
    hazards: ['Carcinogen', 'Strong Oxidizer', 'Toxic'],
    commonConcentrationM: 0.02,
    description: 'Bright orange oxidizer, reduces to chrome green Cr³⁺.',
  },
  na2s2o3: {
    id: 'na2s2o3',
    name: 'Sodium Thiosulfate',
    formula: 'Na₂S₂O₃',
    molarMass: 158.11,
    density: 1.04,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.40)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 70.1,
    hazards: [],
    commonConcentrationM: 0.1,
    description: 'Hypo solution, reacts with acid producing colloidal yellow sulfur turbidity.',
  },

  // ── Insoluble Precipitates & Solids ──
  baso4: {
    id: 'baso4',
    name: 'Barium Sulfate',
    formula: 'BaSO₄(s)',
    molarMass: 233.39,
    density: 4.49,
    type: 'salt',
    baseColor: 'rgba(255, 255, 255, 0.96)', // Dense opaque white
    stateAtRoomTemp: 'solid',
    solubilityLimit: 0.00024,
    hazards: [],
    description: 'Extremely insoluble chalky white precipitate.',
  },
  agcl: {
    id: 'agcl',
    name: 'Silver Chloride',
    formula: 'AgCl(s)',
    molarMass: 143.32,
    density: 5.56,
    type: 'salt',
    baseColor: 'rgba(245, 245, 245, 0.95)', // Curdy white
    stateAtRoomTemp: 'solid',
    solubilityLimit: 0.00019,
    hazards: ['Photosensitive (darkens to purple/grey under light)'],
    description: 'Curdy white precipitate, dissolves in excess ammonium hydroxide.',
  },
  pbi2: {
    id: 'pbi2',
    name: 'Lead(II) Iodide',
    formula: 'PbI₂(s)',
    molarMass: 461.01,
    density: 6.16,
    type: 'salt',
    baseColor: 'rgba(234, 179, 8, 0.98)', // Brilliant golden yellow
    stateAtRoomTemp: 'solid',
    solubilityLimit: 0.076,
    hazards: ['Lead toxicity'],
    description: 'Glistening golden-yellow hexagonal crystalline precipitate ("Golden Rain").',
  },
  caco3: {
    id: 'caco3',
    name: 'Calcium Carbonate',
    formula: 'CaCO₃(s)',
    molarMass: 100.09,
    density: 2.71,
    type: 'salt',
    baseColor: 'rgba(245, 245, 245, 0.92)', // Milky white
    stateAtRoomTemp: 'solid',
    solubilityLimit: 0.0013,
    hazards: [],
    description: 'Fine white suspension causing milkiness in limewater test for CO₂.',
  },
  cu_oh2: {
    id: 'cu_oh2',
    name: 'Copper(II) Hydroxide',
    formula: 'Cu(OH)₂(s)',
    molarMass: 97.56,
    density: 3.37,
    type: 'base',
    baseColor: 'rgba(56, 189, 248, 0.90)', // Pale sky-blue gelatinous
    stateAtRoomTemp: 'solid',
    solubilityLimit: 0.00001,
    hazards: [],
    description: 'Pale blue gelatinous precipitate; dissolves in excess ammonia to deep azure complex.',
  },
  fe_oh2: {
    id: 'fe_oh2',
    name: 'Iron(II) Hydroxide',
    formula: 'Fe(OH)₂(s)',
    molarMass: 89.86,
    density: 3.4,
    type: 'base',
    baseColor: 'rgba(74, 222, 128, 0.85)', // Dirty green
    stateAtRoomTemp: 'solid',
    solubilityLimit: 0.00005,
    hazards: [],
    description: 'Dirty green gelatinous precipitate, oxidizes in air to reddish-brown rust.',
  },
  fe_oh3: {
    id: 'fe_oh3',
    name: 'Iron(III) Hydroxide',
    formula: 'Fe(OH)₃(s)',
    molarMass: 106.87,
    density: 3.4,
    type: 'base',
    baseColor: 'rgba(185, 28, 28, 0.90)', // Reddish-brown rust
    stateAtRoomTemp: 'solid',
    solubilityLimit: 0.000001,
    hazards: [],
    description: 'Reddish-brown foxy precipitate resembling rust.',
  },
  zn_oh2: {
    id: 'zn_oh2',
    name: 'Zinc Hydroxide',
    formula: 'Zn(OH)₂(s)',
    molarMass: 99.42,
    density: 3.05,
    type: 'base',
    baseColor: 'rgba(240, 240, 240, 0.90)', // White gelatinous
    stateAtRoomTemp: 'solid',
    solubilityLimit: 0.00004,
    hazards: [],
    description: 'Amphoteric white gelatinous precipitate; redissolves in excess NaOH or NH₄OH.',
  },
  s_solid: {
    id: 's_solid',
    name: 'Colloidal Sulfur',
    formula: 'S(s)',
    molarMass: 32.06,
    density: 2.07,
    type: 'salt',
    baseColor: 'rgba(253, 224, 71, 0.80)', // Milky pale yellow
    stateAtRoomTemp: 'solid',
    solubilityLimit: 0.000005,
    hazards: [],
    description: 'Pale yellow colloidal sulfur precipitate making solution milky turbid.',
  },

  // ── Metals ──
  zn: {
    id: 'zn',
    name: 'Zinc Granules',
    formula: 'Zn(s)',
    molarMass: 65.38,
    density: 7.14,
    type: 'metal',
    baseColor: 'rgba(148, 163, 184, 1.0)', // Silvery metallic grey
    stateAtRoomTemp: 'solid',
    hazards: ['Flammable with strong oxidizers'],
    description: 'Reactive grey amphoteric metal; reacts with acids releasing rapid H₂ bubbles.',
  },
  cu: {
    id: 'cu',
    name: 'Copper Metal',
    formula: 'Cu(s)',
    molarMass: 63.55,
    density: 8.96,
    type: 'metal',
    baseColor: 'rgba(194, 65, 12, 1.0)', // Metallic reddish bronze
    stateAtRoomTemp: 'solid',
    hazards: [],
    description: 'Reddish-brown noble transition metal; does not displace hydrogen from dilute HCl.',
  },
  fe: {
    id: 'fe',
    name: 'Iron Nails / Filings',
    formula: 'Fe(s)',
    molarMass: 55.85,
    density: 7.87,
    type: 'metal',
    baseColor: 'rgba(100, 116, 139, 1.0)', // Dark steel grey
    stateAtRoomTemp: 'solid',
    hazards: [],
    description: 'Ferromagnetic transition metal; displaces copper from CuSO₄ solution.',
  },
  mg: {
    id: 'mg',
    name: 'Magnesium Ribbon',
    formula: 'Mg(s)',
    molarMass: 24.31,
    density: 1.74,
    type: 'metal',
    baseColor: 'rgba(226, 232, 240, 1.0)', // Bright silvery white
    stateAtRoomTemp: 'solid',
    hazards: ['Highly flammable metal', 'Intense blinding white flame if ignited'],
    description: 'Highly electropositive alkaline earth metal; effervesces vigorously in acid.',
  },
  al: {
    id: 'al',
    name: 'Aluminium Foil / Wire',
    formula: 'Al(s)',
    molarMass: 26.98,
    density: 2.70,
    type: 'metal',
    baseColor: 'rgba(203, 213, 225, 1.0)', // Silvery
    stateAtRoomTemp: 'solid',
    hazards: [],
    description: 'Lightweight amphoteric metal with thin protective oxide passivation layer.',
  },

  // ── Reaction By-Products / Soluble Displacement Salts ──
  zncl2: {
    id: 'zncl2',
    name: 'Zinc Chloride',
    formula: 'ZnCl₂',
    molarMass: 136.30,
    density: 1.05,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.35)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 432,
    hazards: [],
    description: 'Clear soluble zinc salt formed from Zn + 2HCl reaction.',
  },
  znso4: {
    id: 'znso4',
    name: 'Zinc Sulfate',
    formula: 'ZnSO₄',
    molarMass: 161.47,
    density: 1.04,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.35)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 57.7,
    hazards: [],
    description: 'Colorless soluble zinc salt formed in displacement of copper from CuSO₄.',
  },
  mgcl2: {
    id: 'mgcl2',
    name: 'Magnesium Chloride',
    formula: 'MgCl₂',
    molarMass: 95.21,
    density: 1.03,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.35)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 54.3,
    hazards: [],
    description: 'Clear soluble magnesium chloride solution.',
  },
  kno3: {
    id: 'kno3',
    name: 'Potassium Nitrate',
    formula: 'KNO₃',
    molarMass: 101.10,
    density: 1.03,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.35)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 38.3,
    hazards: ['Oxidizer'],
    description: 'Clear neutral nitrate spectator salt.',
  },
  nano3: {
    id: 'nano3',
    name: 'Sodium Nitrate',
    formula: 'NaNO₃',
    molarMass: 84.99,
    density: 1.03,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.35)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 91.2,
    hazards: [],
    description: 'Soluble nitrate spectator salt.',
  },
  ch3coona: {
    id: 'ch3coona',
    name: 'Sodium Acetate',
    formula: 'CH₃COONa',
    molarMass: 82.03,
    density: 1.03,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.35)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 46.5,
    hazards: [],
    description: 'Slightly basic salt formed upon acetic acid neutralization.',
  },

  // ── Gases ──
  h2: {
    id: 'h2',
    name: 'Hydrogen Gas',
    formula: 'H₂(g)',
    molarMass: 2.016,
    density: 0.000089,
    type: 'gas',
    baseColor: 'rgba(255, 255, 255, 0.0)',
    stateAtRoomTemp: 'gas',
    hazards: ['Highly Flammable Gas', 'Explosive pop sound near flame'],
    description: 'Colorless, odorless, highly buoyant flammable gas.',
  },
  co2: {
    id: 'co2',
    name: 'Carbon Dioxide Gas',
    formula: 'CO₂(g)',
    molarMass: 44.01,
    density: 0.00198,
    type: 'gas',
    baseColor: 'rgba(255, 255, 255, 0.0)',
    stateAtRoomTemp: 'gas',
    hazards: ['Asphyxiant in enclosed spaces'],
    description: 'Colorless effervescent gas, extinguishes flame and turns limewater milky.',
  },
  so2: {
    id: 'so2',
    name: 'Sulfur Dioxide Gas',
    formula: 'SO₂(g)',
    molarMass: 64.07,
    density: 0.0026,
    type: 'gas',
    baseColor: 'rgba(255, 255, 255, 0.0)',
    stateAtRoomTemp: 'gas',
    hazards: ['Pungent suffocating odor of burning match', 'Toxic respiratory irritant'],
    description: 'Colorless choking gas evolved during thiosulfate decomposition or sulfide oxidation.',
  },

  // ── Indicators & Specialized Analytical Agents ──
  phenolphthalein: {
    id: 'phenolphthalein',
    name: 'Phenolphthalein Indicator',
    formula: 'C₂₀H₁₄O₄',
    molarMass: 318.32,
    density: 0.98,
    type: 'indicator',
    baseColor: 'rgba(255, 255, 255, 0.0)', // Colorless in acid/neutral
    stateAtRoomTemp: 'aqueous',
    pKa: 9.4,
    hazards: [],
    commonConcentrationM: 0.005,
    description: 'Colorless in acidic/neutral solution (pH < 8.2), turns vivid pink/magenta in alkali (pH > 8.2).',
  },
  methyl_orange: {
    id: 'methyl_orange',
    name: 'Methyl Orange Indicator',
    formula: 'C₁₄H₁₄N₃NaO₃S',
    molarMass: 327.33,
    density: 1.0,
    type: 'indicator',
    baseColor: 'rgba(249, 115, 22, 0.85)', // Orange-red
    stateAtRoomTemp: 'aqueous',
    pKa: 3.47,
    hazards: [],
    commonConcentrationM: 0.005,
    description: 'Red in strong acid (pH < 3.1), orange intermediate (pH 3.1-4.4), yellow in neutral/alkali (pH > 4.4).',
  },
  eriochrome_black_t: {
    id: 'eriochrome_black_t',
    name: 'Eriochrome Black T (EBT)',
    formula: 'C₂₀H₁₂N₃NaO₇S',
    molarMass: 461.38,
    density: 1.0,
    type: 'indicator',
    baseColor: 'rgba(159, 18, 57, 0.85)', // Wine red when bound to Ca/Mg
    stateAtRoomTemp: 'aqueous',
    hazards: [],
    commonConcentrationM: 0.002,
    description: 'Complexometric indicator: wine-red with Ca²⁺/Mg²⁺, turns steel-blue at EDTA endpoint.',
  },
  buffer_ph10: {
    id: 'buffer_ph10',
    name: 'Ammonium Chloride - Ammonia Buffer (pH 10.0)',
    formula: 'NH₄Cl + NH₄OH',
    molarMass: 53.49,
    density: 0.98,
    type: 'base',
    baseColor: 'rgba(248, 250, 252, 0.45)',
    stateAtRoomTemp: 'aqueous',
    hazards: ['Pungent ammonia fumes'],
    commonConcentrationM: 1.0,
    description: 'Alkaline buffer solution maintaining exact pH 10.0 for EDTA water hardness titration.',
  },
  edta: {
    id: 'edta',
    name: 'Disodium EDTA Solution',
    formula: 'Na₂[H₂EDTA]·2H₂O',
    molarMass: 372.24,
    density: 1.02,
    type: 'salt',
    baseColor: 'rgba(248, 250, 252, 0.40)',
    stateAtRoomTemp: 'aqueous',
    hazards: [],
    commonConcentrationM: 0.01,
    description: 'Hexadentate chelating agent that complexes Ca²⁺ and Mg²⁺ in a 1:1 molar ratio.',
  },
  starch: {
    id: 'starch',
    name: 'Starch Indicator Solution',
    formula: '(C₆H₁₀O₅)ₙ',
    molarMass: 162.14,
    density: 1.01,
    type: 'indicator',
    baseColor: 'rgba(241, 245, 249, 0.50)',
    stateAtRoomTemp: 'aqueous',
    hazards: [],
    description: 'Forms an intense dark blue-black inclusion complex with free triiodide (I₃⁻).',
  },
  acetone: {
    id: 'acetone',
    name: 'Acetone (Volatile Organic Solvent)',
    formula: 'C₃H₆O',
    molarMass: 58.08,
    density: 0.79,
    type: 'organic',
    baseColor: 'rgba(240, 249, 255, 0.40)',
    stateAtRoomTemp: 'liquid',
    solubilityLimit: Infinity,
    hazards: ['Highly Flammable Liquid & Vapor', 'Eye & Respiratory Irritant'],
    description: 'Volatile, miscible ketone solvent used for rapid degreasing, rinsing, and drying glassware.',
  },
  chromic_acid: {
    id: 'chromic_acid',
    name: 'Chromic Acid Cleaning Solution',
    formula: 'H₂CrO₄',
    molarMass: 118.01,
    density: 1.20,
    type: 'acid',
    baseColor: 'rgba(234, 88, 12, 0.85)',
    stateAtRoomTemp: 'aqueous',
    pKa: 0.74,
    hazards: ['Strong Oxidizer', 'Corrosive', 'Carcinogen (Cr VI)'],
    commonConcentrationM: 0.5,
    description: 'Powerful oxidizing acid mixture (K₂Cr₂O₇ + conc. H₂SO₄) for stripping stubborn organic film from capillary tubes.',
  },
  liquid_sample_a: {
    id: 'liquid_sample_a',
    name: 'Liquid Sample A (Test Viscosity Sample)',
    formula: 'C₃H₈O₃(aq)',
    molarMass: 92.09,
    density: 1.04,
    type: 'organic',
    baseColor: 'rgba(14, 165, 233, 0.75)',
    stateAtRoomTemp: 'liquid',
    solubilityLimit: Infinity,
    hazards: [],
    description: 'Aqueous calibration test liquid for Ostwald viscometry and relative flow timing.',
  },
  oil_sample: {
    id: 'oil_sample',
    name: 'Vegetable / Lubricating Oil Sample',
    formula: 'R-COOH / Triglyceride',
    molarMass: 282.0,
    density: 0.92,
    type: 'organic',
    baseColor: 'rgba(251, 191, 36, 0.75)',
    stateAtRoomTemp: 'liquid',
    solubilityLimit: 0,
    hazards: [],
    description: 'Fatty acid-containing oil sample undergoing ethanolic KOH titration for acid value determination.',
  },
  cacl2: {
    id: 'cacl2',
    name: 'Calcium Chloride (Standard Hard Water)',
    formula: 'CaCl₂',
    molarMass: 110.98,
    density: 1.02,
    type: 'salt',
    baseColor: 'rgba(240, 249, 255, 0.40)',
    stateAtRoomTemp: 'aqueous',
    solubilityLimit: 74.5,
    hazards: [],
    commonConcentrationM: 0.01,
    description: 'Primary standard for standardizing EDTA solution in water hardness determinations.',
  },
  k2cro4: {
    id: 'k2cro4',
    name: 'Potassium Chromate Indicator',
    formula: 'K₂CrO₄',
    molarMass: 194.19,
    density: 1.05,
    type: 'indicator',
    baseColor: 'rgba(234, 179, 8, 0.85)',
    stateAtRoomTemp: 'aqueous',
    hazards: ['Carcinogen', 'Skin sensitizer'],
    commonConcentrationM: 0.05,
    description: 'Precipitation titration indicator in Mohr method; forms reddish-brown Ag₂CrO₄ at endpoint.',
  },
  mnso4: {
    id: 'mnso4',
    name: 'Manganous Sulfate Solution',
    formula: 'MnSO₄',
    molarMass: 151.00,
    density: 1.08,
    type: 'salt',
    baseColor: 'rgba(253, 230, 138, 0.45)',
    stateAtRoomTemp: 'aqueous',
    hazards: ['Harmful if swallowed'],
    commonConcentrationM: 0.2,
    description: 'Winkler reagent A; reacts with dissolved oxygen to form manganese basic oxide precipitate.',
  },
  buffer_4: {
    id: 'buffer_4',
    name: 'Standard pH 4.00 Calibration Buffer',
    formula: 'KHC₈H₄O₄ (Potassium Hydrogen Phthalate)',
    molarMass: 204.22,
    density: 1.01,
    type: 'acid',
    baseColor: 'rgba(248, 113, 113, 0.45)',
    stateAtRoomTemp: 'aqueous',
    hazards: [],
    commonConcentrationM: 0.05,
    description: 'Standard buffer for calibrating glass electrode on digital pH meters at pH 4.00.',
  },
  buffer_9: {
    id: 'buffer_9',
    name: 'Standard pH 9.20 Calibration Buffer',
    formula: 'Na₂B₄O₇·10H₂O (Borax Buffer)',
    molarMass: 381.37,
    density: 1.01,
    type: 'base',
    baseColor: 'rgba(96, 165, 250, 0.45)',
    stateAtRoomTemp: 'aqueous',
    hazards: [],
    commonConcentrationM: 0.01,
    description: 'Standard buffer for two-point pH meter glass electrode calibration at pH 9.20.',
  },
  neutral_alcohol: {
    id: 'neutral_alcohol',
    name: 'Neutralized Ethanol-Ether Solvent',
    formula: 'C₂H₅OH + (C₂H₅)₂O',
    molarMass: 46.07,
    density: 0.81,
    type: 'organic',
    baseColor: 'rgba(240, 249, 255, 0.35)',
    stateAtRoomTemp: 'liquid',
    solubilityLimit: Infinity,
    hazards: ['Highly Flammable'],
    description: 'Neutralized solvent for dissolving oil sample without contributing to titratable acidity.',
  },
};

/** Helper to retrieve a chemical species by ID or normalized name */
export function getChemicalSpecies(idOrName: string): ChemicalSpecies | undefined {
  let norm = idOrName.toLowerCase().trim().replace(/[-\s]/g, '_');
  if (CHEMICAL_DATABASE[norm]) return CHEMICAL_DATABASE[norm];

  // Common aliases in engineering chemistry experiments
  if (norm.includes('thiosulphate') || norm.includes('thiosulfate')) return CHEMICAL_DATABASE['na2s2o3'];
  if (norm.includes('water') || norm === 'h2o' || norm.includes('cond_water')) return CHEMICAL_DATABASE['h2o'];
  if (norm.includes('sample') && (norm.includes('liquid') || norm.includes('visco'))) return CHEMICAL_DATABASE['liquid_sample_a'];
  if (norm.includes('sample') && (norm.includes('hard') || norm.includes('water') || norm.includes('cacl2'))) return CHEMICAL_DATABASE['cacl2'];
  if (norm.includes('sample') && norm.includes('oil')) return CHEMICAL_DATABASE['oil_sample'];
  if (norm.includes('sample') && norm.includes('hcl')) return CHEMICAL_DATABASE['hcl'];
  if (norm.includes('chromic')) return CHEMICAL_DATABASE['chromic_acid'];
  if (norm.includes('acetone')) return CHEMICAL_DATABASE['acetone'];
  if (norm.includes('ebt') || norm.includes('eriochrome')) return CHEMICAL_DATABASE['eriochrome_black_t'];
  if (norm.includes('phenolphthalein')) return CHEMICAL_DATABASE['phenolphthalein'];
  if (norm.includes('methyl_orange')) return CHEMICAL_DATABASE['methyl_orange'];

  // Try matching by name or formula
  for (const chem of Object.values(CHEMICAL_DATABASE)) {
    if (
      chem.id === norm ||
      chem.name.toLowerCase() === norm ||
      chem.formula.toLowerCase().replace(/[₂₃₄()]/g, '') === norm
    ) {
      return chem;
    }
  }
  return undefined;
}
